### ISSUE TITLE
Addição de novos Modulos para o projeto

### ISSUE THREAD

**Issue by mayronjr** [ES2-UFPI/TourMaker#10]
Para continuar o desenvolvimento do esqueleto do produto, será necessário instalar os seguintes módulos externos:

- @react-native-community/masked-view
- @react-navigation/native
- @react-navigation/stack
- react-native-gesture-handler
- react-native-reanimated
- react-native-safe-area-context
- react-native-screens
- react-native-web

Serão eles usados na melhor gestão das telas que serão exibidas para o usuário.
Estão documentadas em: [https://reactnavigation.org/docs/getting-started/](https://reactnavigation.org/docs/getting-started/)

**Comment by metangross** [comment]
Vai ser necessário a instalação do modulo expo-permissions para o desenvolvimento da Issue #2

**Comment by Marcus-W-Rocha** [comment]
Será necessaria a instalação do package react-native-table-component para exibição de dados ao usuario

**Comment by Marcus-W-Rocha** [comment]
Todos os modulos necessarios para o primeiro sprint foram adicionados

**Comment by Marcus-W-Rocha** [comment]
Será necessaria a instalação do package react-native-dialog-input para nomeação de roteiros salvos

**Comment by mayronjr** [comment]
Será necessária a instalação do modulo expo-google-app-auth para a criação do Login #54
