### ISSUE TITLE
Bug Navigate telas voltando ao inves de criando novas

### ISSUE THREAD

**Issue by Marcus-W-Rocha** [ES2-UFPI/TourMaker#18]
Foi encontrado um bug na implementação da issue #6 na navegação onde quando chamada uma nova tela, o navigate nao gera uma nova, ao inves disso retornando a tela anterior do mesmo tipo da que foi chamada. Bug pode ser encontrado no ultimo comit da branch Marcus#6

**Comment by mayronjr** [comment]
Existe um novo bug encontrado por causa da solução desse bug. Quando estamos editando um roteiro, e excluímos um ponto nessa tela, qualquer mudança posterior a exclusão não é propagada para a tela de Controle de roteiro.
Sugerido abrir issue para a proxima Sprint.
